apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
  name: test-stub
spec:
  image: "quay.io/package-operator/test-stub-package:v1.8.3-2-g293f877"
  config:
    testStubImage: quay.io/package-operator/test-stub:v1.8.3-2-g293f877
